/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddBill: typeof import('./../components/bill/AddBill.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    PageMain: typeof import('./../components/PageMain.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwitchTheme: typeof import('./../components/SwitchTheme.vue')['default']
  }
}
